### ISSUE TITLE
Support Redux (or any state management) Out-of-the-Box?

### ISSUE THREAD

**Issue by SaadBazaz** [mirshko/next-web3-boilerplate#18]
Hey there, 
Thanks for the repo. Was wondering if you plan to support State Management out-of-the-box, it seems important for Metamask to be always connected throughout DApps like the one I'm creating. The could be a yarn command which builds it. Or a cookiecutter template.

**Comment by mirshko** [comment]
So the way web3-react works is through React Context, so we already have the state management needed baked in!

**Comment by SaadBazaz** [comment]
I'll be honest, I didn't really understand things to begin with when starting out with this boilerplate, but with time it got much clearer and I was able to build a beautiful DApp with this in *just one day*. So kudos to your effort! Do you need help in documentation?

**Comment by mirshko** [comment]
Yeah for sure! If you can think of anything that would benefit in documentation please add it to the repo in the README.md, or we can even make a new repo using Nextra for docs if there needs to be more extensive documentation!

**Comment by SaadBazaz** [comment]
I'll leave in a PR or so on the docs when I get free 👍

**Comment by SaadBazaz** [comment]
I'll leave in a PR or so on the docs when I get free 👍
