### ISSUE TITLE
error thrown points at isLoading on Account.js

### ISSUE THREAD

**Issue by bitfede** [mirshko/next-web3-boilerplate#2]
Hey my friend! First of all thank you for providing this useful boilerplate!!! :D

I just have an issue, whenever I render the <Account /> component I get this error in the console:

<img width="335" alt="Screen Shot 2021-04-02 at 1 51 34 AM" src="https://user-images.githubusercontent.com/15684622/113385413-1a247700-9356-11eb-98f5-77270609654c.png">

Which indicates there's a problem with this line of code:

<img width="727" alt="Screen Shot 2021-04-02 at 1 53 12 AM" src="https://user-images.githubusercontent.com/15684622/113385465-358f8200-9356-11eb-8065-f77fe7a3fd9c.png">

So.. What do you suggest me to do? For now the only way to get rid of the error is to remove the prop `isLoading`. Is this a bad solution? Would love to hear some feedback.

Thanks again and have an amazing day!!

**Comment by mirshko** [comment]
Solved it in the latest commit: 80d526ad42e0797a7f73f3a014ae6ab93baa6edc
